# Generated by Django 3.0.7 on 2020-07-10 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 14, 23, 6, 904842, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('last_trans', models.DateTimeField(default=datetime.datetime(2020, 7, 10, 14, 23, 6, 905878, tzinfo=utc), verbose_name='Дата последнего платежа')),
                ('info', models.TextField(default='Info about transaction', verbose_name='Примечания')),
                ('contractid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Users', verbose_name='Номер договора')),
            ],
            options={
                'verbose_name': 'Личный счет',
            },
        ),
    ]
